[2021-10-29 01:19:06,723] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_B scheduled__2021-10-28T00:00:00+00:00 [queued]>
[2021-10-29 01:19:07,240] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_B scheduled__2021-10-28T00:00:00+00:00 [queued]>
[2021-10-29 01:19:07,240] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-29 01:19:07,240] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-29 01:19:07,240] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-29 01:19:07,561] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): training_model_B> on 2021-10-28 00:00:00+00:00
[2021-10-29 01:19:07,862] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_B', 'scheduled__2021-10-28T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpzew5tqvt', '--error-file', '/tmp/tmpjcltjh51']
[2021-10-29 01:19:07,863] {standard_task_runner.py:77} INFO - Job 27: Subtask training_model_B
[2021-10-29 01:19:07,811] {standard_task_runner.py:52} INFO - Started process 1000 to run task
[2021-10-29 01:19:08,806] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.training_model_B scheduled__2021-10-28T00:00:00+00:00 [running]> on host 28ad64d5edf5
[2021-10-29 01:19:09,989] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_B
AIRFLOW_CTX_EXECUTION_DATE=2021-10-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-28T00:00:00+00:00
[2021-10-29 01:19:09,989] {python.py:152} INFO - Done. Returned value was: 6
[2021-10-29 01:19:10,207] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_B, execution_date=20211028T000000, start_date=20211029T011906, end_date=20211029T011910
[2021-10-29 01:19:10,463] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-29 01:19:11,040] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
